language: python

python:
  - "3.9"

install:
  - pip install -r ./docker-compose/requirements.txt
  - pip install flake8

script:
  # para si detecta errores de sintaxis o nombres sin definir
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - python -m unittest discover
